name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
      node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
    - run: npm install

    - name: 'Run tests'
      env: 
        BASE_URL: ${{secrets.BASE_URL}}
        API_GOREST: ${{secrets.API_GOREST}}
      run: node index.js
