name: Node.js Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        env: 
          BASE_URL: ${{secrets.BASE_URL}}
          API_GOREST: ${{secrets.API_GOREST}}
        run: node index.js
